import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Provider } from "react-redux";
import { BrowserRouter } from "react-router-dom";
import { I18nextProvider } from "react-i18next";
import "@arco-design/web-react/dist/css/arco.css";
import "./styles.css";
import i18n from "./app/i18n";
import { store } from "./store";
import App from "./App";
createRoot(document.getElementById("root")!).render(<StrictMode><Provider store={store}><I18nextProvider i18n={i18n}><BrowserRouter><App /></BrowserRouter></I18nextProvider></Provider></StrictMode>);
